# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeName', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=300)),
                ('phi', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcenter.Achievement')),
            ],
        ),
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NumbersLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('pays', models.CharField(max_length=3)),
                ('zone', models.CharField(max_length=1)),
                ('indicatif', models.CharField(max_length=2)),
                ('location_lat', models.CharField(max_length=20)),
                ('location_long', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrecomputeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('text_value', models.TextField(null=True)),
                ('integer_value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentUsername', models.CharField(blank=True, max_length=50, unique=True)),
                ('location_lat', models.CharField(blank=True, max_length=20)),
                ('location_long', models.CharField(blank=True, max_length=20)),
                ('phi', models.IntegerField(blank=True, default=0, null=True)),
                ('phi_multiplier', models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2, null=True)),
                ('first_call_of_the_day', models.DateTimeField(auto_now=True)),
                ('daily_leaderboard', models.IntegerField(default=0)),
                ('daily_leaderboard_calls', models.IntegerField(default=0)),
                ('weekly_leaderboard', models.IntegerField(default=0)),
                ('weekly_leaderboard_calls', models.IntegerField(default=0)),
                ('alltime_leaderboard', models.IntegerField(default=0)),
                ('alltime_leaderboard_calls', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserExtend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='achievementunlock',
            name='userExtend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcenter.UserExtend'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='unlockers',
            field=models.ManyToManyField(related_name='achievements_aux', through='callcenter.AchievementUnlock', to='callcenter.UserExtend'),
        ),
    ]
