# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 17:14
from __future__ import unicode_literals

from django.db import migrations


def add_dcalls(apps, schema_editor):
    PrecomputeData = apps.get_model('callcenter', 'PrecomputeData')
    PrecomputeData.objects.create(
        code='dcalls',
        integer_value=0
    )

def remove_dcalls(apps, schema_editor):
    PrecomputeData = apps.get_model('callcenter', 'PrecomputeData')
    PrecomputeData.objects.filter(code='dcalls').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0003_populate_numberslocations'),
    ]

    operations = [
        migrations.RunPython(add_dcalls, remove_dcalls)
    ]
