# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0007_auto_20170314_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='location_lat',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='location_long',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
