# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0009_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='alltime_leaderboard',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='alltime_leaderboard_calls',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='daily_leaderboard',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='daily_leaderboard_calls',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='weekly_leaderboard',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='weekly_leaderboard_calls',
        ),
    ]
