# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:48
from __future__ import unicode_literals

import csv

from django.db import migrations

def populate_achievements(apps, schema_editor):
    Achievement = apps.get_model("callcenter", "Achievement")
    with open('callcenter/migrations/0011_populate_achievements.tsv', 'r', encoding='utf-8') as f:
        reader = csv.reader(f, delimiter='\t')
        for line in reader:
            pk, name, condition, phi, codeName = line
            Achievement.objects.create(
                pk=pk,
                name=name,
                condition=condition,
                phi=int(phi),
                codeName=codeName
            )


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0010_auto_20170315_2349'),
    ]

    operations = [
        migrations.RunPython(populate_achievements)
    ]
