# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextend',
            old_name='agentKey',
            new_name='ville',
        ),
    ]
