# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0002_auto_20170225_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='phi_multiplier',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
