# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0002_auto_20170209_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementUnlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcenter.Achievement')),
            ],
        ),
        migrations.AlterField(
            model_name='userextend',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserExtend', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievementunlock',
            name='userExtend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callcenter.UserExtend'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='unlockers',
            field=models.ManyToManyField(related_name='achievements_aux', through='callcenter.AchievementUnlock', to='callcenter.UserExtend'),
        ),
    ]
