# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:58
import csv

from django.db import migrations

def populate_numberslocation(apps, schema_editor):
    NumbersLocation = apps.get_model("callcenter", "NumbersLocation")
    with open('callcenter/migrations/0003_populate_numberslocation.tsv', 'r', encoding='utf-8') as f:
        reader = csv.reader(f, delimiter='\t')
        for line in reader:
            code, pays, zone, indicatif, _, location_lat, location_long, _, _ = line
            NumbersLocation.objects.create(
                code=code,
                pays=pays,
                zone=zone,
                indicatif=indicatif,
                location_lat=location_lat,
                location_long=location_long
            )

def truncate_numberslocation(apps, schema_editor):
    NumbersLocation = apps.get_model('callcenter', 'NumbersLocation')
    NumbersLocation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0002_populate_achievements'),
    ]

    operations = [
        migrations.RunPython(populate_numberslocation, truncate_numberslocation)
    ]
