# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0003_auto_20170210_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextend',
            old_name='ville',
            new_name='city',
        ),
    ]
