# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0004_auto_20170210_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='city',
        ),
        migrations.AddField(
            model_name='userextend',
            name='location_lat',
            field=models.CharField(default='lol', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextend',
            name='location_long',
            field=models.CharField(default='lol', max_length=20),
            preserve_default=False,
        ),
    ]
