# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0004_userextend_first_call_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='phi_multiplier',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=2, null=True),
        ),
    ]
