# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 00:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0004_add_dcalls_precomputedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='agentUsername',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UserExtend', to=settings.AUTH_USER_MODEL),
        ),
    ]
