# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0005_auto_20170211_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
