# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0005_auto_20170225_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberslocation',
            name='pays',
            field=models.CharField(max_length=3),
        ),
    ]
