# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0006_userextend_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='location_lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='location_long',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
