# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0006_auto_20170303_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='phi',
            field=models.IntegerField(default=0),
        ),
    ]
