# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0007_auto_20170222_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumbersLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('pays', models.CharField(max_length=2)),
                ('zone', models.CharField(max_length=1)),
                ('indicatif', models.CharField(max_length=2)),
                ('location_lat', models.CharField(max_length=20)),
                ('location_long', models.CharField(max_length=20)),
            ],
        ),
    ]
