# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0009_auto_20170303_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='alltime_leaderboard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextend',
            name='daily_leaderboard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextend',
            name='weekly_leaderboard',
            field=models.IntegerField(default=0),
        ),
    ]
