# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0010_auto_20170307_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='alltime_leaderboard_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextend',
            name='daily_leaderboard_calls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextend',
            name='weekly_leaderboard_calls',
            field=models.IntegerField(default=0),
        ),
    ]
