# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0011_auto_20170307_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecomputeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('text_value', models.TextField(null=True)),
                ('integer_value', models.IntegerField(null=True)),
            ],
        ),
    ]
