# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0012_precomputedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precomputedata',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
