# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='nom de famille')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='Code du pays')),
                ('access_token', models.CharField(blank=True, max_length=255, verbose_name='Access Token')),
            ],
            options={
                'verbose_name_plural': 'utilisateurs',
                'verbose_name': 'utilisateur',
            },
        ),
    ]
